---
- name: Check disk space
  hosts: all
  tasks:
    - name: Run df command
      command: df -h
      register: disk_space

    - name: Print disk space
      debug:
        var: disk_space.stdout
